runtime: python37

env_variables:
#  DATABASE_URL: ''
  FLASK_CONFIG: 'production'
  FLASK_DEBUG: 0
  SECRET_KEY: 'imsorandom'
  ROOT_USER: 'admin@example.com'
  ROOT_PASSWORD: 'Abcd1234!'

entrypoint: gunicorn -b :$PORT manage:app

handlers:
  # This configures Google App Engine to serve the files in the app's static
  # directory.
- url: /static
  static_dir: app/static

  # This handler routes all requests not caught above to your main app. It is
  # required when static routes are defined, but can be omitted (along with
  # the entire handlers section) when there are no static files defined.
- url: /.*
  script: auto